package br.prat.GUI.AdminManage;

import br.prat.controller.controller;
import br.prat.entitys.Feedback;
import br.prat.entitys.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class dashboardFeedbacks extends javax.swing.JFrame {

    controller control;
    Usuario usr;
    //Feedback feed;

    public dashboardFeedbacks(controller control, Usuario usr) {
        initComponents();
        this.control = control;
        this.usr = usr;
        //feed = new Feedback();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPaneLineChart = new javax.swing.JPanel();
        jPaneBarChart = new javax.swing.JPanel();
        jPaneDonutChart = new javax.swing.JPanel();
        jPaneBarVChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPaneLineChart.setLayout(new java.awt.BorderLayout());

        jPaneBarChart.setLayout(new java.awt.BorderLayout());

        jPaneDonutChart.setLayout(new java.awt.BorderLayout());

        jPaneBarVChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPaneBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jPaneBarVChart, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPaneLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPaneDonutChart, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPaneLineChart, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jPaneDonutChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPaneBarVChart, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lineChart();
        honBarChart();
    }//GEN-LAST:event_formWindowOpened

    public void lineChart() {

        XYSeries series = new XYSeries("satifação dos funcionarios com a empresa");

        List<Feedback> listFeed = control.trazerFeedbcks();

        // Usar HashMap para agrupar os valores de perg1 por mês
        Map<Integer, List<Integer>> dadosPorMes = new HashMap<>();

        for (Feedback feed : listFeed) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(feed.getData());
            int mes = cal.get(Calendar.MONTH) + 1; // Mês (1-12)
            int perg1 = feed.getPerg1();

            // Adiciona o valor de perg1 à lista do mês correspondente
            dadosPorMes.computeIfAbsent(mes, k -> new ArrayList<>()).add(perg1);
        }

        // Calcular a média para cada mês
        for (Map.Entry<Integer, List<Integer>> entry : dadosPorMes.entrySet()) {
            int mes = entry.getKey();
            List<Integer> valoresPerg1 = entry.getValue();

            double media = 0;
            if (!valoresPerg1.isEmpty()) {
                for (int valor : valoresPerg1) {
                    media += valor;
                }
                media /= valoresPerg1.size();
            }
            series.add(mes, media); // Adiciona o mês e a média ao gráfico
        }

        XYSeriesCollection dataset = new XYSeriesCollection(series);

        JFreeChart lChart = ChartFactory.createXYLineChart("Grafico de linha",
                "mês", "media por mês", dataset, PlotOrientation.VERTICAL, true, true, false);

        XYPlot linePlot = lChart.getXYPlot();
        linePlot.setBackgroundPaint(Color.white);

        XYLineAndShapeRenderer lineRende = (XYLineAndShapeRenderer) linePlot.getRenderer();
        lineRende.setSeriesPaint(0, Color.RED);

        NumberAxis domainAxis = new NumberAxis("mês");
        //domainAxis.setRange(1, 12);//intervalo do eixo X em meses
        domainAxis.setTickUnit(new NumberTickUnit(1));//incrementa de 1 em 1
        linePlot.setDomainAxis(domainAxis);

        ChartPanel lchart = new ChartPanel(lChart);
        jPaneLineChart.removeAll();
        jPaneLineChart.add(lchart, BorderLayout.CENTER);
        jPaneLineChart.validate();
    }

    public void honBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        List<Feedback> listFeed = control.trazerFeedbcks();

        // Agrupar as notas por setor
        Map<String, List<Integer>> notasPorSetor = new HashMap<>();
        for (Feedback feedback : listFeed) {
            String setor = feedback.getSetor();
            int nota = feedback.getPerg2();
            notasPorSetor.computeIfAbsent(setor, k -> new ArrayList<>()).add(nota);
        }

        // Calcular a média das notas para cada setor
        for (Map.Entry<String, List<Integer>> entry : notasPorSetor.entrySet()) {
            String setor = entry.getKey();
            List<Integer> notas = entry.getValue();
            double media = notas.stream().mapToInt(Integer::intValue).average().orElse(0); // Calcula a média
            dataset.addValue(media, setor, setor); // Adiciona ao dataset.  O terceiro argumento é redundante aqui, mas pode ser útil para legendas mais complexas.
        }

        JFreeChart hBarchart = ChartFactory.createBarChart(
                "barras hon", //titulo
                "categorias", //eixo x
                "valores", //eixo y
                dataset, //dados
                PlotOrientation.HORIZONTAL,
                true, //legenda
                true, //tooltips
                false //url
        );

        ChartPanel hbarchart = new ChartPanel(hBarchart);
        jPaneBarChart.removeAll();
        jPaneBarChart.add(hbarchart, BorderLayout.CENTER);
        jPaneBarChart.validate();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPaneBarChart;
    private javax.swing.JPanel jPaneBarVChart;
    private javax.swing.JPanel jPaneDonutChart;
    private javax.swing.JPanel jPaneLineChart;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
