package br.prat.GUI.AdminManage;

import br.prat.GUI.AdminManage.Funções.criaSetor;
import br.prat.GUI.AdminManage.Funções.editaSetor;
import br.prat.GUI.telaAdmin;
import br.prat.controller.controller;
import br.prat.entitys.Cargo;
import br.prat.entitys.Setor;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class gerenciaFuncoes extends javax.swing.JFrame {

    controller control;
    private telaAdmin telad;

    public gerenciaFuncoes(controller control, telaAdmin telad) {
        initComponents();
        this.control = control;
        this.telad = telad; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSetor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCargo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEditCargo = new javax.swing.JButton();
        btnVolta = new javax.swing.JButton();
        btnApagaSetor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnApagaCargo = new javax.swing.JButton();
        btnCriaSetor = new javax.swing.JButton();
        btnCriaCargo = new javax.swing.JButton();
        btnEditSetor = new javax.swing.JButton();
        btnRecarrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSetor);

        tblCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblCargo);

        jLabel2.setText("Cargos");

        btnEditCargo.setText("editar");

        btnVolta.setText("Voltar");
        btnVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaActionPerformed(evt);
            }
        });

        btnApagaSetor.setText("apagar");
        btnApagaSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagaSetorActionPerformed(evt);
            }
        });

        jLabel1.setText("Setores");

        btnApagaCargo.setText("apagar");

        btnCriaSetor.setText("criar");
        btnCriaSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaSetorActionPerformed(evt);
            }
        });

        btnCriaCargo.setText("criar");

        btnEditSetor.setText("editar");
        btnEditSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSetorActionPerformed(evt);
            }
        });

        btnRecarrega.setText("Recarregar pagina");
        btnRecarrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRecarrega)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnApagaSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCriaSetor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnApagaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVolta)
                                .addComponent(btnCriaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolta)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCriaSetor)
                            .addComponent(btnCriaCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditSetor)
                            .addComponent(btnEditCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApagaSetor)
                            .addComponent(btnApagaCargo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecarrega)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mensagem(String mensagem, String tipo, String titulo){
        JOptionPane optionPane = new JOptionPane(mensagem);
            if (tipo.equals("Info")){
                optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            }
            else if (tipo.equals("Error")){
                optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
            }   
                JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    carregarTabela();
    carregarTabela1();
    }//GEN-LAST:event_formWindowOpened

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        telad.setVisible(true);
        telad.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void btnCriaSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaSetorActionPerformed
        criaSetor criaS = new criaSetor(control);
        
        criaS.setVisible(true);
        criaS.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCriaSetorActionPerformed

    private void btnEditSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSetorActionPerformed
        if (tblSetor.getRowCount() > 0) {
            if (tblSetor.getSelectedRow() != -1) {
                int id_St = Integer.parseInt(
                        String.valueOf(
                                tblSetor.getValueAt(
                                        tblSetor.getSelectedRow(), 0)));
                
                editaSetor editSt = new editaSetor(control, id_St);
                editSt.setVisible(true);
                editSt.setLocationRelativeTo(null);
                   
            }else{
                mensagem("não foi selecionado nenhum registro", "Error", "erro ao editar");
            }
        }else{
            mensagem("tabela vazia nada para eliminar", "Error", "erro ao editar");
        }
    }//GEN-LAST:event_btnEditSetorActionPerformed

    private void btnApagaSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagaSetorActionPerformed
        if (tblSetor.getRowCount() > 0) {
            if (tblSetor.getSelectedRow() != -1) {
                int id_Sto = Integer.parseInt(
                        String.valueOf(
                                tblSetor.getValueAt(
                                        tblSetor.getSelectedRow(), 0)));
                
                control.excluirSetor(id_Sto);
                mensagem("apagado com sucesso", "Info", "dado apagado");
                carregarTabela();      
            }else{
                mensagem("não foi selecionado nenhum registro", "Error", "erro ao apagar");
            }
        }else{
            mensagem("tabela vazia nada para eliminar", "Error", "erro ao apagar");
        }
    }//GEN-LAST:event_btnApagaSetorActionPerformed

    private void btnRecarregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregaActionPerformed
        carregarTabela();
        carregarTabela1();
    }//GEN-LAST:event_btnRecarregaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagaCargo;
    private javax.swing.JButton btnApagaSetor;
    private javax.swing.JButton btnCriaCargo;
    private javax.swing.JButton btnCriaSetor;
    private javax.swing.JButton btnEditCargo;
    private javax.swing.JButton btnEditSetor;
    private javax.swing.JButton btnRecarrega;
    private javax.swing.JButton btnVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCargo;
    private javax.swing.JTable tblSetor;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela(){ 
        //definir a forma que queremos que tenha a tabela
        DefaultTableModel tabelFeed = new DefaultTableModel() {
            //quais linhas e colunas não serão editaveis
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String titulos[] = {"Id","Setor"};
        tabelFeed.setColumnIdentifiers(titulos);
        
        List<Setor> listSetor = control.trazerSetores();
        
        if (listSetor != null) {
            for (Setor setor : listSetor) {
                Object[] objeto = {setor.getId(), setor.getSetor()};
                tabelFeed.addRow(objeto);
            }
            tblSetor.setModel(tabelFeed);
        }
    }
    
    private void carregarTabela1(){ 
        //definir a forma que queremos que tenha a tabela
        DefaultTableModel tabelFeed = new DefaultTableModel() {
            //quais linhas e colunas não serão editaveis
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String titulos[] = {"Id","Cargo"};
        tabelFeed.setColumnIdentifiers(titulos);
        
        List<Cargo> listCargo = control.trazerCargos();
        
        if (listCargo != null) {
            for (Cargo cargo : listCargo) {
                Object[] objeto = {cargo.getId(), cargo.getCargo()};
                tabelFeed.addRow(objeto);
            }
            tblCargo.setModel(tabelFeed);
        }
    }

    //algum dia melhoro essa parte
}
